export const FETCH_ALBUMS = 'FETCH_ALBUMS';
export const UPDATE_ALBUMS = 'UPDATE_ALBUMS';
export const FETCH_PHOTOS_FOR_COUNT = 'FETCH_PHOTOS_FOR_COUNT';
export const UPDATE_PHOTOS_FOR_COUNT = 'UPDATE_PHOTOS_FOR_COUNT';
