export const FETCH_PHOTOS = 'FETCH_PHOTOS';
export const UPDATE_PHOTOS = 'UPDATE_PHOTOS';
export const OPEN_GALLERY_MODAL = 'OPEN_GALLERY_MODAL';
export const CLOSE_GALLERY_MODAL = 'CLOSE_GALLERY_MODAL';
export const GET_PHOTO_INDEX = 'GET_PHOTO_INDEX';
export const UPDATE_PHOTO_INDEX_NEXT = 'UPDATE_PHOTO_INDEX_NEXT';
export const UPDATE_PHOTO_INDEX_PREV = 'UPDATE_PHOTO_INDEX_PREV';
